ExcelAssignment/Controllers/ExpenseCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExcelAssignment.Models;
using Microsoft.AspNetCore.Hosting;

namespace ExcelAssignment.Controllers
{
    public class ExpenseCategoriesController : Controller
    {
        private ApplicationDbContext _context;
        
        public ExpenseCategoriesController(ApplicationDbContext context)
        {
            _context = context;
            

        }

        
        public IActionResult Index()
        {
            return View( _context.ExpenseCategories.AsEnumerable());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( ExpenseCategory expenseCategory)
        {
            if (ModelState.IsValid)
            {
                _context.ExpenseCategories.Add(expenseCategory);
                 _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(expenseCategory);
        }

        
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseCategory = _context.ExpenseCategories.Find(id);
            if (expenseCategory == null)
            {
                return NotFound();
            }
            return View(expenseCategory);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,  ExpenseCategory expenseCategory)
        {
            if (id != expenseCategory.ExCategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.ExpenseCategories.Update(expenseCategory);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseCategoryExists(expenseCategory.ExCategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expenseCategory);
        }

       
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expenseCategory = _context.ExpenseCategories
                .FirstOrDefault(m => m.ExCategoryId == id);
            if (expenseCategory == null)
            {
                return NotFound();
            }

            return View(expenseCategory);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var expenseCategory =  _context.ExpenseCategories.Find(id);
            _context.ExpenseCategories.Remove(expenseCategory);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseCategoryExists(int id)
        {
            return _context.ExpenseCategories.Any(e => e.ExCategoryId == id);
        }
    }
}

ExcelAssignment/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExcelAssignment.Models;
using Microsoft.AspNetCore.Hosting;

namespace ExcelAssignment.Controllers
{
    public class ExpensesController : Controller
    {
        private  ApplicationDbContext _context;
        IWebHostEnvironment _webHostEnvironment;

        public ExpensesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Expenses
        public IActionResult Index(DateTime? StartDate,DateTime? EndDate)
        {
            var exp = _context.Expenses.Include(m => m.ExpenseCategories);
            if (StartDate.HasValue && EndDate.HasValue)
            {
                return View(
                    exp.Where(w => w.ExDate >= StartDate && w.ExDate <= EndDate).AsEnumerable()
                    );
            }
            else
            {
                return View(exp.AsEnumerable());
            }


        }





        public IActionResult Create()
        {
            ViewData["ExCategoryId_FK"] = new SelectList(_context.ExpenseCategories, "ExCategoryId", "ExCategoryName");
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( Expense expense)
        {
            if (ModelState.IsValid)
            {
                _context.Add(expense);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExCategoryId_FK"] = new SelectList(_context.ExpenseCategories, "ExCategoryId", "ExCategoryName", expense.ExCategoryId_FK);
            return View(expense);
        }

        
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = _context.Expenses.Find(id);
            if (expense == null)
            {
                return NotFound();
            }
            ViewData["ExCategoryId_FK"] = new SelectList(_context.ExpenseCategories, "ExCategoryId", "ExCategoryName", expense.ExCategoryId_FK);
            return View(expense);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Expense expense)
        {
            if (id != expense.ExId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expense);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(expense.ExId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExCategoryId_FK"] = new SelectList(_context.ExpenseCategories, "ExCategoryId", "ExCategoryName", expense.ExCategoryId_FK);
            return View(expense);
        }

        
        public IActionResult Delete(int? id)
        {

            try

            {

                var firstEntity = _context.Expenses.Where(c => c.ExId == id).FirstOrDefault();

                _context.Expenses.Remove(firstEntity);

                _context.SaveChanges();

            }

            finally

            {



            }

            return RedirectToAction("Index");

        }


        private bool ExpenseExists(int id)
        {
            return _context.Expenses.Any(e => e.ExId == id);
        }
    }
}

ExcelAssignment/Views/Expenses/Create.cshtml
@model ExcelAssignment.Models.Expense

@{
    ViewData["Title"] = "Create";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>




    <h4>Insert New Data</h4>
    <hr />
    <div class="row ">
        <div class="col-md-4 ">
            <form asp-action="Create" asp-controller="Expenses"
                  data-ajax="true"
                  enctype="multipart/form-data"
                  data-ajax-method="POST"
                  data-ajax-success="OnSuccessFC"
                  data-ajax-failure="OnFailureFC"
                  data-ajax-begin="OnBeginFC"
                  data-ajax-complete="OnCompleteFC">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ExCategoryId_FK" class="control-label"></label>
                    <select asp-for="ExCategoryId_FK" class="form-control" asp-items="ViewBag.ExCategoryId_FK"></select>
                </div>
                <div class="form-group">
                    <label asp-for="ExDate" class="control-label"></label>
                    <input type="date" name="ExDate" id="ExDate" class="form-control" />
                    <span asp-validation-for="ExDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExAmount" class="control-label"></label>
                    <input asp-for="ExAmount" class="form-control" />
                    <span asp-validation-for="ExAmount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="btn btn-secondary" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>

   
    <script>

        function OnSuccessFC(response) {
            alert("OnSuccess");
        }
        function OnFailureFC(response) {
            alert("OnFailure");
        }

        function OnBeginFC() {
            alert("OnBegin");
        }

        function OnCompleteFC() {
            alert("OnComplete");
        }


    </script>
</body>
</html>

ExcelAssignment/Views/Expenses/Edit.cshtml
@model ExcelAssignment.Models.Expense

@{
    Layout = "_Layout";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
</head>
<body>



    <h4>Edit Information</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" data-ajax="true"
                  enctype="multipart/form-data"
                  data-ajax-method="POST"
                  data-ajax-success="OnSuccessFE"
                  data-ajax-failure="OnFailureFE"
                  data-ajax-begin="OnBeginFE"
                  data-ajax-complete="OnCompleteFE">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ExId" />
                <div class="form-group">
                    <label asp-for="ExCategoryId_FK" class="control-label"></label>
                    <select asp-for="ExCategoryId_FK" class="form-control" asp-items="ViewBag.ExCategoryId_FK"></select>
                    <span asp-validation-for="ExCategoryId_FK" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExDate" class="control-label"></label>
                    <input type="date" asp-for="ExDate" name="ExDate"  class="form-control" />
                    <span asp-validation-for="ExDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExAmount" class="control-label"></label>
                    <input asp-for="ExAmount" class="form-control" />
                    <span asp-validation-for="ExAmount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload" class="btn btn-primary" />
                    <a class="btn btn-secondary" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>

    <script>

        function OnSuccessFE(response) {
            alert("OnSuccess");
        }
        function OnFailureFE(response) {
            alert("OnFailure");
        }

        function OnBeginFE() {
            alert("OnBegin");
        }

        function OnCompleteFE() {
            alert("OnComplete");
        }


    </script>


</body>
</html>

ExcelAssignment/Views/Expenses/Index.cshtml
@model IEnumerable<ExcelAssignment.Models.Expense>

@{
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <form asp-action="Index" asp-controller="Expenses">


        <span class="btn btn-outline-primary" >StartDate :</span> <input type="date" name="StartDate" />
        <span class="btn btn-outline-success" >EndDate :</span > <input type="date" name="EndDate" />
        <input class="btn btn-success" type="submit" value="Get Records" />

    </form>
    <div>
        <h2>All Expense information</h2>
    </div>

    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
        <a class="btn btn-secondary" asp-action="Index" asp-controller="ExpenseCategories">  ExpenseCategory </a>
    </p>
    <table  class="table table-striped table-bordered  table-dark table-sm  ">
        <thead>
            <tr>
                <th scope="col">
                    ExpanseDate
                </th>
                <th scope="col">
                  ExpanseAmount
                </th>
                <th scope="col">
                    ExpenseCategory
                </th>
                <th scope="col">Action</th="col">
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.ExDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExAmount)
                    </td>
                    <td >
                        @Html.DisplayFor(modelItem => item.ExpenseCategories.ExCategoryName )
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ExId"class="badge badge-warning">Update</a> |
                        <a asp-action="Delete" asp-route-id="@item.ExId"class="badge badge-danger">Remove</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>